export default {
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
    SET_SORT: 'SET_SORT',
    SORTED_BY_ALL: 'SORTED_BY_ALL',
    SORTED_BY_COMPLETE: 'SORTED_BY_COMPLETE',
    SORTED_BY_UNCOMPLETE: 'SORTED_BY_UNCOMPLETE',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}